user_age = input("what's your age: 10")
print("as user said, he is ", user_age)
user_name = input("what's your name: ilia ")
print("as user said, he is ", user_name)
user_lastname=input("what's your lastname:lobjanidze ")
print("as user said, he is ", user_lastname)
user_momsname=input("what's your momsname: maia")
print("as user said, he is ", user_momsname)
user_dadsname=input("what's your dadsname: gia")
print("as user said, he is ", user_dadsname)
user_petsname=input("what's your petsname: i dont have a pet")
print("as user said, he is ", user_petsname)
user_10=input("how old are you gonna be 15 years later:25")
print("as user said, he is ", user_10+15)

